// This file is automatically generated by the export-package plugin. Do not edit it manually.
export const MajorVersion = 1;
export const MinorVersion = 3;
export const PatchVersion = 12097930;
export const VersionNumber = `${MajorVersion}.${MinorVersion}.${PatchVersion}`;
